### ISSUE TITLE
Gift shopping demo flow browser test

### ISSUE THREAD

**Issue by mariakleiner** [PolymerLabs/arcs-cdn#107]

**Comment by smalls** [comment]
See PolymerLabs/arcs#454.

**Comment by smalls** [comment]
I think this is done - @mmandlis let me know if I'm mistaken.

**Comment by mariakleiner** [comment]
I was planning to add more steps to the gift shopping test - click 'Add' to move products to shortlist, and to accept next stage suggestions. Shall I file a matching bug under arcs/?

**Comment by smalls** [comment]
Gotcha, that makes sense - I've filed https://github.com/PolymerLabs/arcs/issues/727 in arcs for the remaining work.
