### ISSUE TITLE
Create arc description and render/edit in title.

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs-cdn#12]
Create arc description and render in title.
Click on title makes it editable.

**Comment by seefeldb** [comment]
13db1da866d6dde4050687745c3a8127e5fd5db4 as first step

remaing:
- recalculate description from arc, instead of polling database. find some reasonable interval to update (as it captures the data).
- make title editable

**Comment by smalls** [comment]
Now https://github.com/PolymerLabs/arcs/issues/724.
