### ISSUE TITLE
Don't show all suggestions by default

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs-cdn#139]
In 0.2, the behavior was:
 - empty query shows only suggestions that fill a slot in the current view (i.e. don't go into the root slot)
 - enter on an empty query inserts '*'
 - '*' shows all suggestions

When we added the toproot, those suggestions showed up, but really should have been ignored in the same way as those that go into 'root'.

Can we replicate the behavior, incl. toproot fix, in 0.3?

We have too many suggestions – and they'll quickly grow – for the whole list to be a good experience..

**Comment by sjmiles** [comment]
Should be finished as of 0a3fde20c9f561ee353e69cb16f067dc7e410fec
