### ISSUE TITLE
Fix tests after merging ES module based app shell.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs-cdn#142]
Preparing to land the `es6-modulify` branch. Known items to resolve subsequently:

- gift shopping demo flow selenium test is broken (actual test seems to duplicate the final clause in the description text incorrectly, perhaps a template issue)
- `arc-app.html` not yet converted, thus `app-shell.html` still remains as well. Possible cdn path construction issue to resolve.
- unit tests for `persistent-arc.html`, `dancing-dots.html`, and `good-map.html` are disabled as they need to import the involved code which now lives in ES modules. Fixing may require emulating what `arcs` does via `sigh test` to generate and run mocha tests in a manner as touched upon in https://github.com/mochajs/mocha/issues/3006

FYI @sjmiles

**Comment by sjmiles** [comment]
- localize dependencies instead of list in AppShell.js
- remove window globals for ArcsUtils and Xen*

**Comment by shaper** [comment]
Only one item remains: "...unit tests for persistent-arc.html, dancing-dots.html, and good-map.html..."

**Comment by smalls** [comment]
Now tracked by https://github.com/PolymerLabs/arcs/issues/713.
