### ISSUE TITLE
Gift shopping demo flow is broken.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs-cdn#168]
Filing issue to track broken test as discussed in chat yesterday. @mmandlis I am happy to look at this as well but assigning to you first since it relates to your change.

It looks like the product specific subids change breaks the gift shopping demo flow selenium test for some reason, this commit: https://github.com/PolymerLabs/arcs/commit/b27a91ad867944b570cd28ba1b04766331a327fd

```
There's no error shot, it's an assert failure: `[chrome #0-0] 1) test Arcs demo flows can use the gift shopping demo flow:
[chrome #0-0] false == true
[chrome #0-0] AssertionError [ERR_ASSERTION]: false == true
[chrome #0-0]     at Context.<anonymous> (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs-cdn/dev/test/specs/starter-test.js:413:12)
[chrome #0-0]     at new Promise (<anonymous>)
[chrome #0-0]     at new F (/usr/local/google/home/wkorman/workspace/shaper-arcs/arcs-cdn/node_modules/core-js/library/modules/_export.js:35:28)`
assert.ok(annotations.length > 0 && annotations.every(a => a.length > 0));
```

**Comment by mariakleiner** [comment]
this is now fixed.

**Comment by shaper** [comment]
FTR was fixed by https://github.com/PolymerLabs/arcs-cdn/commit/7031538beb74ce5c265cd3eef2ff84f438eb1291

**Comment by shaper** [comment]
Ah missed your reference LOL email
