### ISSUE TITLE
Fix `npm test` to work on Windows.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs-cdn#180]
@sjmiles noted while doing dev on Windows, we can test on my Windows workstation together soon:

- Probably need to prefix the `tools ...` commands with `node` since the `#!` atop the tools scripts isn't sufficient for Windows.
- Subsequently he sees an error that looks like Windows specific file path reference issue: `Error: no test file found at path */test/index.test.html.`

**Comment by smalls** [comment]
Moved to https://github.com/PolymerLabs/arcs/issues/711.
