### ISSUE TITLE
Recipe for a basic user meta data profile arc

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs-cdn#22]
Everything about a user except the GUID should be stored in profile arcs. We need one to cover the basics like
* name
* avatar

Let's create a very simple recipe & particle to cover this, incl. just picking avatars from a pre-defined set or whatever other flow makes this simple.

**Comment by shaper** [comment]
Maybe this would be a not unreasonable starter-ish thing for me. @sjmiles @smalls

**Comment by smalls** [comment]
I believe this is done.
