### ISSUE TITLE
friend's shared variables don't appear in context

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs-cdn#25]
I just made favoritefood a variable (so that descriptions work better), but that now broke suggestions for other friend's favorite foods. It's odd that it works for profile and not shared arcs.

**Comment by noelutz** [comment]
Tested profile variables. They work for me.

I think the issue is related to sharing overall. Flagging an Arc as being shared doesn't flag the Arc as shared in Firebase anymore. Looking.

**Comment by noelutz** [comment]
Variable syncing with friends works for me. There was a small race that manifested itself because of the longer latency I experience here when sharing an Arc. I fixed that.

Can you show me an example where it doesn't work? Here's an example that does work:
https://polymerlabs.github.io//arcs-cdn/dev/apps/web/?solo=https://noelutz.github.io/arcs-stories/0.2/Testing/Testing.recipes

**Comment by seefeldb** [comment]
https://polymerlabs.github.io/arcs-cdn/dev/apps/web/?solo=https://seefeldb.github.io/arc-stories/0.2/Restaurants/Restaurants.recipes&amkey=-KwvORfgcw19KLV8H-Rh gets you a suggestion if you are "Bob", but not when you are "Smitty", even though Bob is Smitty's friend.

**Comment by seefeldb** [comment]
Use https://polymerlabs.github.io/arcs-cdn/dev/apps/web/?solo=https://seefeldb.github.io/arc-stories/0.2/Identity/Identity.recipes to set favorite food. Just tried it again from scratch and it didn't work. But I don't see the difference to your testing recipes and manifests. Hmm.

**Comment by noelutz** [comment]
In the example you showed me the Arc was flagged as profile but not as shared. I flagged the favorite food Arc as shared and then opened up a Smitty Arc: https://polymerlabs.github.io/arcs-cdn/dev/apps/web/?solo=https://seefeldb.github.io/arc-stories/0.2/Restaurants/Restaurants.recipes&user=Smitty&amkey=-Kwx_-V0kW183ZXsJ34j

Following suggestion appeared after adding restaurants: https://screenshot.googleplex.com/jCseBaZ8uvE

Seems to work fine. Can you try again?

**Comment by seefeldb** [comment]
Doh! It works, thanks!
