### ISSUE TITLE
Set up prettier.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs-cdn#33]
https://github.com/prettier/prettier

@smalls has done some local work here. Presume we'd want a way to run it with a config locally, and also a way to have it run as part of presubmit.

@sjmiles to review/edit config.

both @smalls and myself wished we had auto-format when reading extension code in review for https://github.com/PolymerLabs/arcs/pull/500

**Comment by smalls** [comment]
I went down the path of looking into integrating this into vim. [vim-prettier](https://github.com/prettier/vim-prettier) looks like it'll work.

@sjmiles are you running prettier before you commit code, or do you have it integrated into your editor?

**Comment by shaper** [comment]
I ran it manually on extension code just to see:

https://github.com/PolymerLabs/arcs/pull/507

**Comment by shaper** [comment]
Tracking to be replaced by `clang-format` per @dstockwell "Lint and Format" document shared separately. That doc is focused on https://github.com/PolymerLabs/arcs but ideally we'd use same approach for https://github.com/PolymerLabs/arcs-cdn.
