### ISSUE TITLE
Synthetic handle descriptions for shared handles

### ISSUE THREAD

**Issue by noelutz** [PolymerLabs/arcs-cdn#35]
In appshell1 storage shared handles that got pulled into the local context were set a custom (or synthetic) description to make suggestions more humanly readable.

E.g., for a handle tagged #giftlist or named giftlist the description would either be 'my giftlist' or '<b>Matt's</b> giftlist' depending on who the owner of the handle is.

This seems like a useful feature to reproduce.

```
_getViewDescription(name, tags, user, owner) {
      let noun = (user == owner) ? 'my' : `<b>${owner}'s</b>`;
      if (tags && tags.length) {
        return `${noun} ${tags[0].substring(1)}`;
      }
      if (name) {
        return `${noun} ${name}`;
      }
}
```

**Comment by smalls** [comment]
Now tracked by https://github.com/PolymerLabs/arcs/issues/719.
