### ISSUE TITLE
Pass suggestions-element to the slot composer

### ISSUE THREAD

**Issue by mariakleiner** [PolymerLabs/arcs-cdn#80]
to properly create suggestions (similar to the change:
https://github.com/PolymerLabs/arcs/commit/95a1c94dec16eb2331aec94215e89acf8ec3650a#diff-bb5f1da3491bde37be05eb33223c488e)

**Comment by smalls** [comment]
Now tracked by https://github.com/PolymerLabs/arcs/issues/717.

**Comment by mariakleiner** [comment]
This was fixed by PolymerLabs/arcs-cdn#127
