### ISSUE TITLE
Remember external recipes when used and surface in launcher somehow.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs-cdn#97]
If a user uses a third party recipe via `solo` or `manifest` we might want to remember that and surface it in some most-frequently/recently-used list manner in the launcher.

Having a more robust registry/strategizer/etc. seems the long term approach but for now maybe we'd beneift from something more low-fidelity.

This could be crazy, so filing for discussion. @seefeldb @smalls

**Comment by shaper** [comment]
@mmandlis also for any input.

**Comment by smalls** [comment]
Now tracked as https://github.com/PolymerLabs/arcs/issues/715.
