### ISSUE TITLE
Allow recipes/particles to specify icon(s) to show in the app shell.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs-cdn#99]
The icons currently are placeholders. Probably we'll want something fancy eventually to illustrate the set of icons in the involved recipes/particles. @smalls and I had some interesting ideas talking in person just now including a Super Mario esque map. :smiley_cat: 

Maybe for now just having a way for particles to specify their icon and having the app shell do the simplest possible thing to end up with an icon list in `ArcMetadata` and then pick the last one would at least make things a little less random feeling and more developer empowering.

**Comment by smalls** [comment]
To expand the map idea, as you move through an arc you have a linear path behind you, but many options ahead. An icon that reflects this (and maybe that you can expand to see a visualization of where you are in the journey) might be useful feedback for users.

**Comment by smalls** [comment]
Now tracked as https://github.com/PolymerLabs/arcs/issues/714.
